# Generated by Django 4.2.3 on 2025-07-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mgnifam",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_size", models.IntegerField()),
                ("protein_rep", models.IntegerField()),
                ("rep_region", models.TextField()),
                ("rep_length", models.IntegerField()),
                ("converged", models.BooleanField()),
                ("plddt", models.FloatField()),
                ("ptm", models.FloatField()),
                ("helix_percent", models.FloatField()),
                ("strand_percent", models.FloatField()),
                ("coil_percent", models.FloatField()),
                ("rep_sequence", models.TextField()),
                ("consensus", models.TextField()),
                ("seed_msa_blob", models.BinaryField(default=None, null=True)),
                ("hmm_blob", models.BinaryField(default=None, null=True)),
                ("rf_blob", models.BinaryField(default=None, null=True)),
                ("cif_blob", models.BinaryField(default=None, null=True)),
                ("biome_blob", models.BinaryField(default=None, null=True)),
                ("domain_blob", models.BinaryField(default=None, null=True)),
                ("s4pred_blob", models.BinaryField(default=None, null=True)),
            ],
            options={
                "db_table": "mgnifam",
            },
        ),
        migrations.CreateModel(
            name="MgnifamPfams",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pfam", models.CharField(max_length=16)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("prob", models.FloatField()),
                ("e_value", models.FloatField()),
                ("length", models.IntegerField()),
                ("query_hmm", models.TextField()),
                ("template_hmm", models.TextField()),
                (
                    "mgnifam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.mgnifam",
                    ),
                ),
            ],
            options={
                "db_table": "mgnifam_pfams",
            },
        ),
        migrations.CreateModel(
            name="MgnifamFunfams",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("funfam", models.TextField()),
                ("e_value", models.FloatField()),
                ("score", models.FloatField()),
                ("hmm_from", models.IntegerField()),
                ("hmm_to", models.IntegerField()),
                ("ali_from", models.IntegerField()),
                ("ali_to", models.IntegerField()),
                ("env_from", models.IntegerField()),
                ("env_to", models.IntegerField()),
                ("acc", models.FloatField()),
                (
                    "mgnifam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.mgnifam",
                    ),
                ),
            ],
            options={
                "db_table": "mgnifam_funfams",
            },
        ),
        migrations.CreateModel(
            name="MgnifamFolds",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fold", models.TextField()),
                ("aligned_length", models.IntegerField()),
                ("q_start", models.IntegerField()),
                ("q_end", models.IntegerField()),
                ("t_start", models.IntegerField()),
                ("t_end", models.IntegerField()),
                ("e_value", models.FloatField()),
                (
                    "mgnifam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="explorer.mgnifam",
                    ),
                ),
            ],
            options={
                "db_table": "mgnifam_folds",
            },
        ),
    ]
