# Generated by Django 4.2.3 on 2024-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mgnifamfolds",
            old_name="mgnifam_id",
            new_name="mgnifam",
        ),
        migrations.RenameField(
            model_name="mgnifampfams",
            old_name="mgnifam_id",
            new_name="mgnifam",
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="biomes_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="cif_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="domain_architecture_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="hmm_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="msa_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="rf_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="seed_msa_blob",
            field=models.BinaryField(null=True),
        ),
    ]
