# Generated by Django 4.2.3 on 2024-12-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mgnifam",
            name="pred_secondary_structure_blob",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="mgnifam",
            name="pred_secondary_structure_file",
            field=models.TextField(null=True),
        ),
    ]
