---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: mgnifams-hl-exp
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: proxy-config
      namespace: mgnifams-hl-exp
    data:
      HTTP_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      HTTPS_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"
      http_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      https_proxy: "http://hh-wwwcache.ebi.ac.uk:3128"
      no_proxy: "localhost,.cluster.local"
      ALLOWED_HOST: "mgnifams-demo.mgnify.org"

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mgnifams-site
      namespace: mgnifams-hl-exp
      labels:
        app: mgnifams-site
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mgnifams-site
      template:
        metadata:
          labels:
            app: mgnifams-site
        spec:
          securityContext:
            runAsUser: 7123
            runAsGroup: 1347
          volumes:
            - name: mgnifams-app-storage
              persistentVolumeClaim:
                claimName: mgnifams-volume-claim-2
          containers:
            - image: quay.io/microbiome-informatics/mgnifams_site:ebi-wp-k8s-hl
              imagePullPolicy: Always
              name: mgnifams-site
              envFrom:
                - secretRef:
                    name: mgnifams-secret
                - configMapRef:
                    name: proxy-config
              ports:
                - containerPort: 8000
                  name: django
              volumeMounts:
              - mountPath: "/app/dbs"
                name: mgnifams-app-storage
          imagePullSecrets:
            - name: quay-pull-secret
  - apiVersion: v1
    kind: Service
    metadata:
      name: mgnifams-site
      namespace: mgnifams-hl-exp
      labels:
        app: mgnifams-site
    spec:
      type: NodePort
      selector:
        app: mgnifams-site
      ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: mgnifams-ingress
      namespace: mgnifams-hl-exp
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: mgnifams-demo.mgnify.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: mgnifams-site
                    port:
                      number: 8000
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mgnifams-vol-2
      namespace: mgnifams-hl-exp
    spec:
      capacity:
        storage: 300Gi
      volumeMode: Filesystem
      accessModes:
        - ReadOnlyMany
      persistentVolumeReclaimPolicy: Recycle
      mountOptions:
        - nfsvers=3
      nfs:
        server: hh-isi-srv-vlan1496.ebi.ac.uk
        path: /ifs/public/services/metagenomics/mgnifams/dbs
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mgnifams-volume-claim-2
      namespace: mgnifams-hl-exp
    spec:
      storageClassName: ""
      accessModes:
        - ReadOnlyMany
      resources:
        requests:
          storage: 300Gi
      volumeName: mgnifams-vol-2


